// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxOlIAMKTZIXgmjwDbJOSmm9Mi387W8bo',
    appId: '1:827644807709:web:10cc1fceef03c1f8f9d4f4',
    messagingSenderId: '827644807709',
    projectId: 'pasal-backend',
    authDomain: 'pasal-backend.firebaseapp.com',
    storageBucket: 'pasal-backend.appspot.com',
    measurementId: 'G-5JT9Z5T0LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhppqAav5FMatcm2yPhS8BI46C7D8gvnM',
    appId: '1:827644807709:android:d76dee8e78eca67af9d4f4',
    messagingSenderId: '827644807709',
    projectId: 'pasal-backend',
    storageBucket: 'pasal-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQBykoZD1xErcshw5HcJqUG3GOVmUErDs',
    appId: '1:827644807709:ios:abd85d9a66fe9fd0f9d4f4',
    messagingSenderId: '827644807709',
    projectId: 'pasal-backend',
    storageBucket: 'pasal-backend.appspot.com',
    iosBundleId: 'com.example.pasal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQBykoZD1xErcshw5HcJqUG3GOVmUErDs',
    appId: '1:827644807709:ios:abd85d9a66fe9fd0f9d4f4',
    messagingSenderId: '827644807709',
    projectId: 'pasal-backend',
    storageBucket: 'pasal-backend.appspot.com',
    iosBundleId: 'com.example.pasal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxOlIAMKTZIXgmjwDbJOSmm9Mi387W8bo',
    appId: '1:827644807709:web:df60d0e6742aa735f9d4f4',
    messagingSenderId: '827644807709',
    projectId: 'pasal-backend',
    authDomain: 'pasal-backend.firebaseapp.com',
    storageBucket: 'pasal-backend.appspot.com',
    measurementId: 'G-6QPKXCN9HX',
  );
}
